### ISSUE TITLE
Request for List of Python Package Versions

### ISSUE THREAD

**Issue by Boyle-Coffee** [lccurious/MuLTI#1]
Hello. I'm currently using your Python library, and I need a list of all the Python packages it depends on, along with their version numbers. This information will help me ensure compatibility and maintain the library effectively. Thank you!

**Comment by lccurious** [comment]
The requirements.txt has been updated. Please be aware that there are some bugs in the 'geoopt' lib. After installing it with pip, someone might need to manually update the source code of this package according to this issue: https://github.com/geoopt/geoopt/pull/219. I am working on modifying the repository to compute the gradient without relying on external libraries.
